[general]
import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
  "./key_bindings.toml"
]
live_config_reload = true

[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
# decorations ="Buttonless"
decorations_theme_variant = "Dark"
startup_mode = "Maximized"
dynamic_padding = true
opacity = 0.8
blur = true
option_as_alt ="Both"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 0

[scrolling]
history = 10000
multiplier = 1

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
