[general]
import = [
  "~/.config/alacritty/themes/themes/aura.toml",
  "./key_bindings.toml"
]
live_config_reload = true

[env]
TERM = "alacritty"

[font]
size = 14.0
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 0 }

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
# decorations ="Buttonless"
decorations_theme_variant = "Dark"
startup_mode = "Maximized"
# dynamic_padding = true
opacity = 0.85
blur = true
option_as_alt ="Both"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 4

[scrolling]
history = 10000
multiplier = 1

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
